package com.ouseworks.game.ecs;

public enum EventType {
    COUNTER_CLICKED_BY_CHEF1,
    ORDER_COMPLETED,
    INCORRECT_ORDER,
    GAME_FINISHED,
    REQUEST_BURGER,
    REQUEST_SALAD,
    CHECK_INTERACTIONS,
    INGREDIENT_STATION,
    PREPARTION_STATION,
    COOKING_STATION,
    USE_COOKING_STATION,
    USE_PREPARATION_STATION,
    UPDATE_INVENTORY,
    CHOP_LETTUCE,
    CHOP_TOMATO,
    CHOP_ONION,
    ASSEMBLE_BURGER,
    ASSEMBLE_SALAD
}
